name: PR Checks
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
jobs:
  jira-check:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request title rules
        uses: deepakputhraya/action-pr-title@v1.0.2
        with:
          regex: '[A-Z]{2,}-\d+' # Regex the title should match.